-- Amazon-themed MySQL assignment
-- Dr. Subramani

-- Assignment Questions:
-- 1. List all customers who have made purchases one of more than $80.
select 
	users.name AS Customers_name, 
    users.membership, 
    SUM(orders.total_amount) AS Total_spent 
FROM users 
LEFT JOIN orders
USING(user_id)
GROUP BY users.user_id
HAVING Total_spent > 80;

-- 2. Retrieve all orders placed in the last 280 days along with the customer name and email.
SELECT
users.name,
users.email,
orders.order_id,
orders.order_date
FROM
orders 
LEFT JOIN users
USING(user_id)
WHERE orders.order_date >= DATE_SUB(CURDATE(), INTERVAL 280 DAY)
ORDER BY orders.order_date DESC;

-- 3. Find the average product price for each category?
SELECT category, AVG(price) AS Average_price FROM products GROUP BY category;

-- 4. List all customers who have purchased a product from the category Electronics.?
SELECT users.name, products.category 
FROM users
JOIN orders ON users.user_id = orders.user_id
JOIN orderdetails ON orders.order_id = orderdetails.order_id
JOIN products ON orderdetails.product_id = products.product_id
WHERE products.category = "Electronics"; 

-- 5. Find the total number of products sold and the total revenue generated for each product?
SELECT 
orderdetails.product_id, 
products.Name AS product_name,
sum(orderdetails.quantity) AS total_quantity_sold,
sum(orderdetails.quantity * products.price) AS total_revenue
FROM orderdetails 
JOIN products ON orderdetails.product_id = products.product_id
GROUP BY orderdetails.product_id;

-- 6. Update the price of all products in the Books category, increasing it by 10% Query.
SELECT 
name AS Product_Name, 
category, 
price AS old_Price, 
(price+(price * 0.10)) AS New_Price 
FROM products WHERE category="Books";

UPDATE products SET price = (price+(price * 0.10)) WHERE category = "Books";


-- 7. Remove all orders that were placed before 2020.
DELETE FROM orders where order_date < '2020-01-01';  

-- 8. Write a query to fetch the order details, including customer name, product name, and
-- quantity, for orders placed on 2024-05-01.

SELECT
users.name AS Customer_Name,
products.name AS Ordered_Product,
orderdetails.quantity AS Ordered_Quantity,
orders.order_date AS Order_Date
From users 
JOIN orders ON users.user_id = orders.user_id
JOIN orderdetails ON orders.order_id = orderdetails.order_id
JOIN products ON orderdetails.product_id = products.product_id
WHERE orders.order_date = "2024-05-01";

-- 9. Fetch all customers and the total number of orders they have placed.
SELECT 
users.user_id AS Customers_ID,
users.name AS Customers_Name,
COUNT(orderdetails.product_id) AS Total_Number_Of_Ordered,
Sum(orderdetails.quantity) AS Total_Quantity
FROM users
LEFT JOIN orders ON users.user_id = orders.user_id
JOIN orderdetails ON orders.order_id = orderdetails.order_id
GROUP BY users.name, users.user_id ;

-- 10. Retrieve the average rating for all products in the Electronics category.
-- No rating column exists in the current database

-- 11. List all customers who purchased more than 1 units of any product, including the product
-- name and total quantity purchased.
SELECT 
users.user_id AS Customers_ID,
users.name AS Customers_Name,
products.name AS Product_Name,
COUNT(orderdetails.product_id) AS Total_Number_Of_Ordered,
Sum(orderdetails.quantity) AS Total_Quantity
FROM users
LEFT JOIN orders ON users.user_id = orders.user_id
JOIN orderdetails ON orders.order_id = orderdetails.order_id
JOIN products ON orderdetails.product_id = products.product_id
GROUP BY users.name, users.user_id, products.name
HAVING Total_Quantity > 1;

-- 12. Find the total revenue generated by each category along with the category name.
SELECT 
products.category AS Product_category,
sum(orderdetails.quantity) AS Total_quantity_sold,
sum(orderdetails.quantity * products.price) AS Total_revenue
FROM products
LEFT JOIN orderdetails ON orderdetails.product_id = products.product_id
GROUP BY products.category;

SELECT * from orders;




